### ISSUE TITLE
which python version should we use for best out come?

### ISSUE THREAD

**Issue by zerishpho** [doronz88/harlogger#1]
prime@Primes-MacBook-Pro harlogger-master % ./remote_har_listener.py -o output.har
Traceback (most recent call last):
  File "/Users/prime/Downloads/harlogger-master/harlogger-master/./remote_har_listener.py", line 151, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/prime/Downloads/harlogger-master/harlogger-master/./remote_har_listener.py", line 109, in main
    assert line == b'[connected]'
AssertionError

**Comment by doronz88** [comment]
Should work with every python3.x.
The script executes `idevicesyslog` to parse the log lines from the device. 
This `assert` line doesn't really matter, but is there just for sanity check since I expect the first line from it to be "[connected]".
Can you try and print the line you're getting instead? Or just comment out and verify?

On newer releases I'll replace this dependency with: https://github.com/doronz88/pymobiledevice3 which I'm currently working on to reduce dependency on external executables.

Please update what solution fixes this.

**Comment by doronz88** [comment]
It's now using `pymobiledevice3` which is a much better implementation and should fix all enviornment related bugs. I'm closing this issue. If the problem persist, please open another.

**Comment by zerishpho** [comment]
thank you
